version: 2
updates:
  - package-ecosystem: npm
    directory: /frontend/portfolio-spa
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - frontend
    commit-message:
      prefix: 'chore(deps):'

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - backend
    commit-message:
      prefix: 'chore(deps):'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - root
    commit-message:
      prefix: 'chore(deps):'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: 'ci(deps):'
